export const SUBMISSIONS_BUCKET = 'submissions'
export const EQUIPMENT_RENTAL_BUCKET = 'equipment-rentals'
export const PROFILE_PHOTOS_BUCKET = 'profile-photos'
export const TEACHER_RECEIPTS_BUCKET = 'teacher-receipts'
export const VALUE_ANALYSIS_BUCKET = 'value-analysis'
