import Link from "next/link"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import ClientClockInitializer from "@/components/ClientClockInitializer"
import DateUtil from "@/lib/date-util"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  DateUtil.clearServerClock()
  DateUtil.initServerClock()
  const serverNow = DateUtil.nowUTC().toISOString()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientClockInitializer serverNow={serverNow} />
        <div className="min-h-screen bg-slate-50">
          <header className="border-b border-slate-200 bg-white">
            <div className="mx-auto flex max-w-6xl items-center justify-end px-4 py-3">
              <Link
                href="/dashboard"
                className="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50 hover:text-slate-900"
              >
                대시보드로 이동
              </Link>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  )
}
