import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import ClientClockInitializer from "@/components/ClientClockInitializer"
import DateUtil from "@/lib/date-util"

import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  DateUtil.clearServerClock()
  DateUtil.initServerClock()
  const serverNow = DateUtil.nowUTC().toISOString()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientClockInitializer serverNow={serverNow} />
        {children}
      </body>
    </html>
  )
}
